apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-banking-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: openbanking.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-banking-svc
                port:
                  number: 8090
