apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.meta.deployment.name }}
  labels: {{ toYaml .Values.meta.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ toYaml .Values.meta.labels | nindent 6 }}
  template:
    metadata:
      labels: {{ toYaml .Values.meta.labels | nindent 8 }}
    spec:
      volumes: {{ toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Values.chart.name }}
          image: "{{ .Values.host.repo.local }}/{{ .Values.chart.name }}:{{ .Values.chart.app.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          volumeMounts: {{ toYaml .Values.volumeMounts | nindent 12 }}
          envFrom: {{ toYaml .Values.host.envFrom | nindent 12 }}
          env: {{ toYaml .Values.host.env | nindent 12 }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecret | nindent 8 }}