apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.service.name }}
spec:
  selector: {{ toYaml .Values.meta.labels | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8092
  type: NodePort