apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsn-back-deploy
  labels:
    app: shopsn-back-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsn-back-deploy
  template:
    metadata:
      name: shopsn-back-deploy
      labels:
        app: shopsn-back-deploy
    spec:
      containers:
        - name: shopsn-back-deploy
          image: host.minikube.internal:8082/backend.shop.sn:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8099
              protocol: TCP
      restartPolicy: Always
      