apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopsn-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-local
spec:
  ingressClassName: nginx
  rules:
    - host: shopsn.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopsn-front-svc
                port:
                  number: 4210
    - host: api-shopsn.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopsn-svc
                port:
                  number: 8099
  tls:
    - hosts:
        - api-shopsn.127.0.0.1.nip.io
        - shopsn.127.0.0.1.nip.io
      secretName: shopsn-tls