apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopsn-front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: shop.sn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopsn-front-svc
                port:
                  number: 4210
    - host: api.shop.sn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopsn-svc
                port:
                  number: 8099
