apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: charles-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNhVENDQVZFQ0FRQXdKREVRTUE0R0ExVUVBd3dIWTJoaGNteGxjekVRTUE0R0ExVUVDZ3dIYkdWaGNtNWwNCmNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU53ejZHdnBnYTJCRElOQWNJTHkNCm9JRUo1bUpPNmxwY2pWUWRuNnplaWpVTnR2ZTM1ZXFxZ2c2RlF4K3hHb084YUs3Y3hIc1ZWSmJVRzl0UUlEcXMNCnB1cXhqYWY2dG5mN01pdlpGeG1PR2hTWXR3cllMMHJJOThwdzJCL3hKZm1FamdMOUszSWxKVGZsVUpSd25sb2MNClBYbXJFZUJlSDR1K0VnMFdsM3JuVlVNaGR2SEpVWDhTVHdQVkhmTTJvaGovUnBJaDN3bTdiN0xjNHJKWVVaQk4NCmYzRlN6WHNveXNhQXRja0hpNVV5dmZ2TnNOdGprSllwcU9RWTdxQjREanZNcU94VlJic2xkQjQ4OThodzc1MmcNCisySGtrV1YrVzVZSnY4NjVqVVBIQ3REeHBhNmFRSkFzS3R0YlNCZzlHSzRjVXcvNlFidmhuNjFQSVVDdi90Y3ENCkV3MENBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmpxL1p3cFA4Y2loZWRBcndYbmtLR0QrQ2wNCkNPK2FYT3VYNjFlYTRiN21PQ3RSa3dzRFQwdzFnWEN1R0ZpY2phaThFdkNOK3lwSDFvQW03UldidU1RUUtzZG4NCmNBd1dKangwMWMvYU1OekxwUGxhMm1qYzVjWjlHRXhaaTN6YThDMkN4b3VaTGN6UzlvbkEyakVraHNOcGxQSVYNCnczYWJPYWZHQnNadHppREpodVlwbnh2VURrc0ZuZG16T01SMUtsaW5qbXJZazVYcjBRK0Z0OFVaWGoveVdHRUkNCkFHdTA3L3FWQ3FjVGdaKzYxM1p1N05sQUVXUmhUZElKZEFmYTBzWjVpSXRZcklUcHFtalhPUTMxYXNBMmRzZU0NCnZkYXYydTRCZmRuWi8vSGsrSmdmb3h0bmlkVWxuLzNpZms5cGVPRGlWUFRxS2tFUDVNcXgwOVdMTWYyYw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth