apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}-rollout
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.host }}/{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{ toYaml .Values.environment | nindent 12 }}
          {{ toYaml .Values.db.env | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port.containerPort }}
              hostPort: {{ .Values.service.port.hostPort }}
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            periodSeconds: 7
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
  {{- if eq .Values.deployment.strategy "canary" }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 60 }
        - setWeight: 40
        - pause: { duration: 10 }
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
  revisionHistoryLimit: 2
  {{- end }}
