apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.hostPort }}
      targetPort: {{ .Values.service.port.containerPort }}
  selector:
    app: {{ .Values.app.name }}